export const reportData = [
    {
      leadid: "YNzUVN1c4PmTG7bTkuzRg",
      leaddate: "10/26/2023 0:00:00",
      leadcheckin: "10/28/2023 0:00:00",
      leadcheckout: "10/29/2023 0:00:00",
      bookingid: " ",
      bookingdate: " ",
      bookingcheckindate: " ",
      bookingcheckoutdate: " ",
      revenue: "0.211625",
      commission: "0.105813",
      languagecode: "EN",
      devicecategory: "1",
      clientcountrycode: "MY",
      brandid: "573418",
      label: " ",
      hotelid: "-100",
      hotelcountry: "Not Applicable",
      hotelcity: "Not Applicable",
      hotelname: "Not Applicable",
      transactiontype: "Click",
      transactiontypecode: "1",
      transactionstatus: "Active",
      transactionstatuscode: "1",
      vertical: "Hotel",
      pvalue: " ",
      eid: "FALSE",
      pid: " ",
      cid: " ",
      lid: " ",
      integrationcode: "kan_262812_573418",
      bookings: " ",
    },
    {
        leadid: "_GAm39OWP48RSDHCD0C_iw",
        leaddate: "10/11/2023 0:00:00",
        leadcheckin: "10/29/2023 0:00:00",
        leadcheckout: "10/31/2023 0:00:00",
        bookingid: " ",
        bookingdate: " ",
        bookingcheckindate: " ",
        bookingcheckoutdate: " ",
        revenue: "0",
        commission: "0",
        languagecode: "EN",
        devicecategory: "0",
        clientcountrycode: "MY",
        brandid: "573418",
        label: " ",
        hotelid: "-100",
        hotelcountry: "Not Applicable",
        hotelcity: "Not Applicable",
        hotelname: "Not Applicable",
        transactiontype: "Click",
        transactiontypecode: "1",
        transactionstatus: "Active",
        transactionstatuscode: "1",
        vertical: "Flight",
        pvalue: " ",
        eid: "FALSE",
        pid: " ",
        cid: " ",
        lid: " ",
        integrationcode: "kan_262812_573418",
        bookings: " ",
      },
      {
        leadid: "0fBUbrtlhY90TBBiSh5D_g",
        leaddate: "10/11/2023 0:00:00",
        leadcheckin: "10/11/2023 0:00:00",
        leadcheckout: "10/12/2023 0:00:00",
        bookingid: " ",
        bookingdate: " ",
        bookingcheckindate: " ",
        bookingcheckoutdate: " ",
        revenue: "0.222349",
        commission: "0.111174",
        languagecode: "EN",
        devicecategory: "0",
        clientcountrycode: "MY",
        brandid: "573418",
        label: " ",
        hotelid: "-100",
        hotelcountry: "Not Applicable",
        hotelcity: "Not Applicable",
        hotelname: "Not Applicable",
        transactiontype: "Click",
        transactiontypecode: "1",
        transactionstatus: "Active",
        transactionstatuscode: "1",
        vertical: "Hotel",
        pvalue: " ",
        eid: "FALSE",
        pid: " ",
        cid: " ",
        lid: " ",
        integrationcode: "kan_262812_573418",
        bookings: " ",
      },
      {
        leadid: "10IVowgeqo5_QI8Dr$kRyQ",
        leaddate: "10/11/2023 0:00:00",
        leadcheckin: "10/29/2023 0:00:00",
        leadcheckout: "10/31/2023 0:00:00",
        bookingid: " ",
        bookingdate: " ",
        bookingcheckindate: " ",
        bookingcheckoutdate: " ",
        revenue: "0.238876",
        commission: "0.119438",
        languagecode: "EN",
        devicecategory: "0",
        clientcountrycode: "MY",
        brandid: "573418",
        label: " ",
        hotelid: "-100",
        hotelcountry: "Not Applicable",
        hotelcity: "Not Applicable",
        hotelname: "Not Applicable",
        transactiontype: "Click",
        transactiontypecode: "1",
        transactionstatus: "Active",
        transactionstatuscode: "1",
        vertical: "Flight",
        pvalue: " ",
        eid: "FALSE",
        pid: " ",
        cid: " ",
        lid: " ",
        integrationcode: "kan_262812_573418",
        bookings: " ",
      },
      {
        leadid: "1cAregJDbJ8DRN4Mh0LBxQ",
        leaddate: "10/10/2023 0:00:00",
        leadcheckin: "10/16/2023 0:00:00",
        leadcheckout: "10/16/2023 0:00:00",
        bookingid: " ",
        bookingdate: " ",
        bookingcheckindate: " ",
        bookingcheckoutdate: " ",
        revenue: "0.3",
        commission: "0.15",
        languagecode: "EN",
        devicecategory: "0",
        clientcountrycode: "MY",
        brandid: "573418",
        label: " ",
        hotelid: "-100",
        hotelcountry: "Not Applicable",
        hotelcity: "Not Applicable",
        hotelname: "Not Applicable",
        transactiontype: "Click",
        transactiontypecode: "1",
        transactionstatus: "Active",
        transactionstatuscode: "1",
        vertical: "Flight",
        pvalue: " ",
        eid: "FALSE",
        pid: " ",
        cid: " ",
        lid: " ",
        integrationcode: "kan_262812_573418",
        bookings: " ",
      },
      {
        leadid: "2G$KVINw5YoNSPLE0rY1UQ",
        leaddate: "10/16/2023 0:00:00",
        leadcheckin: "10/13/2023 0:00:00",
        leadcheckout: "10/16/2023 0:00:00",
        bookingid: " ",
        bookingdate: " ",
        bookingcheckindate: " ",
        bookingcheckoutdate: " ",
        revenue: "0",
        commission: "0",
        languagecode: "EN",
        devicecategory: "0",
        clientcountrycode: "MY",
        brandid: "573418",
        label: " ",
        hotelid: "-100",
        hotelcountry: "Not Applicable",
        hotelcity: "Not Applicable",
        hotelname: "Not Applicable",
        transactiontype: "Click",
        transactiontypecode: "1",
        transactionstatus: "Active",
        transactionstatuscode: "1",
        vertical: "Flight",
        pvalue: " ",
        eid: "FALSE",
        pid: " ",
        cid: " ",
        lid: " ",
        integrationcode: "kan_262812_573418",
        bookings: " ",
      },
      {
        leadid: "2rRD9DPnSIokQCktDyg1Mg",
        leaddate: "10/26/2023 0:00:00",
        leadcheckin: "10/28/2023 0:00:00",
        leadcheckout: "10/29/2023 0:00:00",
        bookingid: " ",
        bookingdate: " ",
        bookingcheckindate: " ",
        bookingcheckoutdate: " ",
        revenue: "0.105812",
        commission: "0.052906",
        languagecode: "EN",
        devicecategory: "1",
        clientcountrycode: "MY",
        brandid: "573418",
        label: " ",
        hotelid: "-100",
        hotelcountry: "Not Applicable",
        hotelcity: "Not Applicable",
        hotelname: "Not Applicable",
        transactiontype: "Click",
        transactiontypecode: "1",
        transactionstatus: "Active",
        transactionstatuscode: "1",
        vertical: "Hotel",
        pvalue: " ",
        eid: "FALSE",
        pid: " ",
        cid: " ",
        lid: " ",
        integrationcode: "kan_262812_573418",
        bookings: " ",
      },
      {
        leadid: "2XqX$bkoj7U1Q2hkebwjdQ",
        leaddate: "10/11/2023 0:00:00",
        leadcheckin: "10/29/2023 0:00:00",
        leadcheckout: "10/31/2023 0:00:00",
        bookingid: " ",
        bookingdate: " ",
        bookingcheckindate: " ",
        bookingcheckoutdate: " ",
        revenue: "0.238876",
        commission: "0.119438",
        languagecode: "EN",
        devicecategory: "0",
        clientcountrycode: "MY",
        brandid: "573418",
        label: " ",
        hotelid: "-100",
        hotelcountry: "Not Applicable",
        hotelcity: "Not Applicable",
        hotelname: "Not Applicable",
        transactiontype: "Click",
        transactiontypecode: "1",
        transactionstatus: "Active",
        transactionstatuscode: "1",
        vertical: "Flight",
        pvalue: " ",
        eid: "FALSE",
        pid: " ",
        cid: " ",
        lid: " ",
        integrationcode: "kan_262812_573418",
        bookings: " ",
      },
      {
        leadid: "3bgK3pKrHqYdRDkgQdZOrg",
        leaddate: "10/14/2023 0:00:00",
        leadcheckin: "11/08/2023 0:00:00",
        leadcheckout: "11/12/2023 0:00:00",
        bookingid: " ",
        bookingdate: " ",
        bookingcheckindate: " ",
        bookingcheckoutdate: " ",
        revenue: "0",
        commission: "0",
        languagecode: "EN",
        devicecategory: "1",
        clientcountrycode: "MY",
        brandid: "573418",
        label: " ",
        hotelid: "-100",
        hotelcountry: "Not Applicable",
        hotelcity: "Not Applicable",
        hotelname: "Not Applicable",
        transactiontype: "Click",
        transactiontypecode: "1",
        transactionstatus: "Active",
        transactionstatuscode: "1",
        vertical: "Flight",
        pvalue: " ",
        eid: "FALSE",
        pid: " ",
        cid: " ",
        lid: " ",
        integrationcode: "kan_262812_573418",
        bookings: " ",
      },
      {
        leadid: "24cBHmMv5l73sS7td_W3tVw",
        leaddate: "10/11/2023 0:00:00",
        leadcheckin: "10/29/2023 0:00:00",
        leadcheckout: "10/31/2023 0:00:00",
        bookingid: " ",
        bookingdate: " ",
        bookingcheckindate: " ",
        bookingcheckoutdate: " ",
        revenue: "0.5",
        commission: "0.25",
        languagecode: "EN",
        devicecategory: "0",
        clientcountrycode: "MY",
        brandid: "573418",
        label: " ",
        hotelid: "-100",
        hotelcountry: "Not Applicable",
        hotelcity: "Not Applicable",
        hotelname: "Not Applicable",
        transactiontype: "Click",
        transactiontypecode: "1",
        transactionstatus: "Active",
        transactionstatuscode: "1",
        vertical: "Flight",
        pvalue: " ",
        eid: "FALSE",
        pid: " ",
        cid: " ",
        lid: " ",
        integrationcode: "kan_262812_573418",
        bookings: " ",
      },
      {
        leadid: "7AHu97SPSYwISlxJXiu9BQ",
        leaddate: "10/11/2023 0:00:00",
        leadcheckin: "10/16/2023 0:00:00",
        leadcheckout: "10/17/2023 0:00:00",
        bookingid: " ",
        bookingdate: " ",
        bookingcheckindate: " ",
        bookingcheckoutdate: " ",
        revenue: "0.3",
        commission: "0.15",
        languagecode: "EN",
        devicecategory: "0",
        clientcountrycode: "MY",
        brandid: "573418",
        label: " ",
        hotelid: "-100",
        hotelcountry: "Not Applicable",
        hotelcity: "Not Applicable",
        hotelname: "Not Applicable",
        transactiontype: "Click",
        transactiontypecode: "1",
        transactionstatus: "Active",
        transactionstatuscode: "1",
        vertical: "Flight",
        pvalue: " ",
        eid: "FALSE",
        pid: " ",
        cid: " ",
        lid: " ",
        integrationcode: "kan_262812_573418",
        bookings: " ",
      },
      {
        leadid: "7e8SDWw08opbTI1WsUfnng",
        leaddate: "10/11/2023 0:00:00",
        leadcheckin: "10/29/2023 0:00:00",
        leadcheckout: "10/31/2023 0:00:00",
        bookingid: " ",
        bookingdate: " ",
        bookingcheckindate: " ",
        bookingcheckoutdate: " ",
        revenue: "0",
        commission: "0",
        languagecode: "EN",
        devicecategory: "0",
        clientcountrycode: "MY",
        brandid: "573418",
        label: " ",
        hotelid: "-100",
        hotelcountry: "Not Applicable",
        hotelcity: "Not Applicable",
        hotelname: "Not Applicable",
        transactiontype: "Click",
        transactiontypecode: "1",
        transactionstatus: "Active",
        transactionstatuscode: "1",
        vertical: "Flight",
        pvalue: " ",
        eid: "FALSE",
        pid: " ",
        cid: " ",
        lid: " ",
        integrationcode: "kan_262812_573418",
        bookings: " ",
      },
      {
        leadid: "90VaskwE8YLXRsNtAkuESg",
        leaddate: "10/06/2023 0:00:00",
        leadcheckin: "10/02/2023 0:00:00",
        leadcheckout: "10/05/2023 0:00:00",
        bookingid: " ",
        bookingdate: " ",
        bookingcheckindate: " ",
        bookingcheckoutdate: " ",
        revenue: "0",
        commission: "0",
        languagecode: "EN",
        devicecategory: "1",
        clientcountrycode: "MY",
        brandid: "573418",
        label: " ",
        hotelid: "448682",
        hotelcountry: "Macau",
        hotelcity: "Macau",
        hotelname: "Sheraton Grand Macao",
        transactiontype: "Click",
        transactiontypecode: "1",
        transactionstatus: "Active",
        transactionstatuscode: "1",
        vertical: "Hotel",
        pvalue: " ",
        eid: "FALSE",
        pid: " ",
        cid: " ",
        lid: " ",
        integrationcode: "kan_262812_573418",
        bookings: " ",
      },
      {
        leadid: "9blcabb78LYTRI0FMEJ3uw",
        leaddate: "10/18/2023 0:00:00",
        leadcheckin: "10/19/2023 0:00:00",
        leadcheckout: "10/22/2023 0:00:00",
        bookingid: " ",
        bookingdate: " ",
        bookingcheckindate: " ",
        bookingcheckoutdate: " ",
        revenue: "0",
        commission: "0",
        languagecode: "EN",
        devicecategory: "0",
        clientcountrycode: "MY",
        brandid: "573418",
        label: " ",
        hotelid: "-100",
        hotelcountry: "Not Applicable",
        hotelcity: "Not Applicable",
        hotelname: "Not Applicable",
        transactiontype: "Click",
        transactiontypecode: "1",
        transactionstatus: "Active",
        transactionstatuscode: "1",
        vertical: "Flight",
        pvalue: " ",
        eid: "FALSE",
        pid: " ",
        cid: " ",
        lid: " ",
        integrationcode: "kan_262812_573418",
        bookings: " ",
      },
      {
        leadid: "bgwC72Rq67KGSuQxKviIfw",
        leaddate: "10/24/2023 0:00:00",
        leadcheckin: "10/29/2023 0:00:00",
        leadcheckout: "10/31/2023 0:00:00",
        bookingid: "1080493230",
        bookingdate: "10/24/2023 0:00:00",
        bookingcheckindate: "10/29/2023 0:00:00",
        bookingcheckoutdate: "10/31/2023 0:00:00",
        revenue: "6.53",
        commission: "3.265",
        languagecode: "EN",
        devicecategory: "0",
        clientcountrycode: "MY",
        brandid: "573418",
        label: " ",
        hotelid: "-100",
        hotelcountry: "Not Applicable",
        hotelcity: "Not Applicable",
        hotelname: "Not Applicable",
        transactiontype: "Booking",
        transactiontypecode: "10",
        transactionstatus: "Active",
        transactionstatuscode: "1",
        vertical: "Flight",
        pvalue: " ",
        eid: "FALSE",
        pid: " ",
        cid: " ",
        lid: " ",
        integrationcode: "kan_262812_573418",
        bookings: " ",
      },
      {
        leadid: "BiT4fnncCqx7QBahbltl3w",
        leaddate: "10/26/2023 0:00:00",
        leadcheckin: "10/28/2023 0:00:00",
        leadcheckout: "10/29/2023 0:00:00",
        bookingid: " ",
        bookingdate: " ",
        bookingcheckindate: " ",
        bookingcheckoutdate: " ",
        revenue: "0",
        commission: "0",
        languagecode: "EN",
        devicecategory: "1",
        clientcountrycode: "MY",
        brandid: "573418",
        label: " ",
        hotelid: "252793",
        hotelcountry: "Malaysia",
        hotelcity: "Petaling Jaya",
        hotelname: "Eastin Hotel Kuala Lumpur",
        transactiontype: "Click",
        transactiontypecode: "1",
        transactionstatus: "Active",
        transactionstatuscode: "1",
        vertical: "Hotel",
        pvalue: " ",
        eid: "FALSE",
        pid: " ",
        cid: " ",
        lid: " ",
        integrationcode: "kan_262812_573418",
        bookings: " ",
      },
      {
        leadid: "yaAD_c8pEIEeTagWimPLFA",
        leaddate: "10/08/2023 0:00:00",
        leadcheckin: "10/09/2023 0:00:00",
        leadcheckout: "10/10/2023 0:00:00",
        bookingid: " ",
        bookingdate: " ",
        bookingcheckindate: " ",
        bookingcheckoutdate: " ",
        revenue: "0.211698",
        commission: "0.105849",
        languagecode: "EN",
        devicecategory: "1",
        clientcountrycode: "MY",
        brandid: "573418",
        label: " ",
        hotelid: "-100",
        hotelcountry: "Not Applicable",
        hotelcity: "Not Applicable",
        hotelname: "Not Applicable",
        transactiontype: "Click",
        transactiontypecode: "1",
        transactionstatus: "Active",
        transactionstatuscode: "1",
        vertical: "Flight",
        pvalue: " ",
        eid: "FALSE",
        pid: " ",
        cid: " ",
        lid: " ",
        integrationcode: "kan_262812_573418",
        bookings: " ",
      },
      {
        leadid: "yJSV6ggSnJJHQUJbo$9CNg",
        leaddate: "10/11/2023 0:00:00",
        leadcheckin: "10/29/2023 0:00:00",
        leadcheckout: "10/31/2023 0:00:00",
        bookingid: " ",
        bookingdate: " ",
        bookingcheckindate: " ",
        bookingcheckoutdate: " ",
        revenue: "0.4",
        commission: "0.15",
        languagecode: "EN",
        devicecategory: "0",
        clientcountrycode: "MY",
        brandid: "573418",
        label: " ",
        hotelid: "-100",
        hotelcountry: "Not Applicable",
        hotelcity: "Not Applicable",
        hotelname: "Not Applicable",
        transactiontype: "Click",
        transactiontypecode: "1",
        transactionstatus: "Active",
        transactionstatuscode: "1",
        vertical: "Flight",
        pvalue: " ",
        eid: "FALSE",
        pid: " ",
        cid: " ",
        lid: " ",
        integrationcode: "kan_262812_573418",
        bookings: " ",
      },
      {
        leadid: "Yqwx4CjajoYSQwodsIcCQA$9CNg",
        leaddate: "10/11/2023 0:00:00",
        leadcheckin: "10/29/2023 0:00:00",
        leadcheckout: "10/31/2023 0:00:00",
        bookingid: " ",
        bookingdate: " ",
        bookingcheckindate: " ",
        bookingcheckoutdate: " ",
        revenue: "0.3",
        commission: "0.15",
        languagecode: "EN",
        devicecategory: "0",
        clientcountrycode: "MY",
        brandid: "573418",
        label: " ",
        hotelid: "-100",
        hotelcountry: "Not Applicable",
        hotelcity: "Not Applicable",
        hotelname: "Not Applicable",
        transactiontype: "Click",
        transactiontypecode: "1",
        transactionstatus: "Active",
        transactionstatuscode: "1",
        vertical: "Flight",
        pvalue: " ",
        eid: "FALSE",
        pid: " ",
        cid: " ",
        lid: " ",
        integrationcode: "kan_262812_573418",
        bookings: " ",
      },
      {
        leadid: "v0h3MsM2Ba9QQt$4q3SEnw",
        leaddate: "10/13/2023 0:00:00",
        leadcheckin: "10/13/2023 0:00:00",
        leadcheckout: "10/14/2023 0:00:00",
        bookingid: " ",
        bookingdate: " ",
        bookingcheckindate: " ",
        bookingcheckoutdate: " ",
        revenue: "0",
        commission: "0",
        languagecode: "EN",
        devicecategory: "0",
        clientcountrycode: "MY",
        brandid: "573418",
        label: " ",
        hotelid: "4260794",
        hotelcountry: "Malaysia",
        hotelcity: "george Town",
        hotelname: "Ropewalk Piazza Hotel By Phc",
        transactiontype: "Click",
        transactiontypecode: "1",
        transactionstatus: "Active",
        transactionstatuscode: "1",
        vertical: "Hotel",
        pvalue: " ",
        eid: "FALSE",
        pid: " ",
        cid: " ",
        lid: " ",
        integrationcode: "kan_262812_573418",
        bookings: " ",
      },
      {
        leadid: "vPI14EsLAKaNQubC0RzmfQ",
        leaddate: "10/26/2023 0:00:00",
        leadcheckin: "10/28/2023 0:00:00",
        leadcheckout: "10/29/2023 0:00:00",
        bookingid: " ",
        bookingdate: " ",
        bookingcheckindate: " ",
        bookingcheckoutdate: " ",
        revenue: "0",
        commission: "0",
        languagecode: "EN",
        devicecategory: "1",
        clientcountrycode: "MY",
        brandid: "573418",
        label: " ",
        hotelid: "252793",
        hotelcountry: "Malaysia",
        hotelcity: "Petaling Jaya",
        hotelname: "Eastin Hotel Kuala Lumpur",
        transactiontype: "Click",
        transactiontypecode: "1",
        transactionstatus: "Active",
        transactionstatuscode: "1",
        vertical: "Hotel",
        pvalue: " ",
        eid: "FALSE",
        pid: " ",
        cid: " ",
        lid: " ",
        integrationcode: "kan_262812_573418",
        bookings: " ",
      },
  ];
  