export const ticketData = [
    {
      from: "Melaka Sentral",
      to: "Larkin Sentral",
      date: "28 Sep 2023",
      company: "KKKL SDN BHD (Terus Nanti)",
      time: "8:30AM",
      seat: "28, 29",
      ref: "99093198471029",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/QR_Code_Example.svg/1200px-QR_Code_Example.svg.png",
      booking: "GO20231206EMDS",
      trip: "MLK01",
      gate: "B",
      platform: "3",
      name:"Hazwan",
      ic:"990111-11-1273",
    },
    {
      from: "Larkin Sentral",
      to: "Melaka Sentral",
      date: "30 Sep 2023",
      company: "KKKL SDN BHD (Terus Nanti)",
      time: "8:30AM",
      seat: "28, 29",
      ref: "99093198452312",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/QR_Code_Example.svg/1200px-QR_Code_Example.svg.png",
      booking: "GO20231207EMDS",
      trip: "LRK02",
      gate: "A",
      platform: "1",
      name:"Hazwan",
      ic:"990111-11-1273",
    },
];

export const bookingDetails = {

    "status": true,
    "message": null,
    "code": null,
    "data": {
        "bookingNo": "GO20231206EMDS",
        "balance": 0,
        "totalPrice": 108.50,
        "mdRegionInfoCurrencySymbol": "MYR",
        "bookingStatus": "confirm",
        "bookingPaymentStatus": "paid",
        "userId": "82f8ee9f-c98e-4e35-8db0-b0b300ee9e11",
        "totalPriceBalance": 0,
        "refundAmount": 0.00,
        "goTicketingBooking": {
            "bookingOn": "2023-12-06T16:53:31.21",
            "intg_BookingNo": "GEB-Test20231206884C",
            "totalPrice": 108.50,
            "mdRegionInfoCurrencySymbol": "MYR",
            "goTicketingBookingStatus": "confirm",
            "userId": "82f8ee9f-c98e-4e35-8db0-b0b300ee9e11",
            "passengerPax": 2,
            "totalTicket": 2,
            "totalTicketPrice": 106.50,
            "totalGoPass": 0,
            "totalGoPassPrice": 0,
            "totalInsurance": 2,
            "totalInsurancePrice": 2.00,
            "totalFacilityCharge": 0,
            "totalAdminFee": 0.00,
            "bookingList": [
                {
                    "operatorBookingNo": null,
                    "operatorName": "Delima",
                    "operatorCode": "DELIMA",
                    "operatorCompanyCode": "DELIMAV",
                    "operatorCompanyName": "Delima Vision",
                    "operatorCompanyLogo": "https://goticketing.blob.core.windows.net/operatorcompany/907edea2-00bd-44d1-bef1-e6aae9aa00dc.png",
                    "operatorCompanyLogo_120x30": "https://goticketing.blob.core.windows.net/operatorcompany/0b395f89-1d05-4516-b3f9-dd5399914617.png",
                    "operatorCompanyLogo_120x70": "https://goticketing.blob.core.windows.net/operatorcompany/8403b691-6b0c-4b7e-b0e3-42e305b6c671.png",
                    "operatorCompanyLogo_144x90": "https://goticketing.blob.core.windows.net/operatorcompany/a1b2adba-8043-4650-8e6d-95566c90d68e.png",
                    "tripCode": "KLG002",
                    "mdTerminalNameFrom": "Larkin Sentral",
                    "mdTerminalCodeFrom": "LAR",
                    "mdTerminalNameTo": "Melaka Sentral",
                    "mdTerminalCodeTo": "MEL",
                    "totalPrice": 108.50,
                    "departDateTime": "2023-12-07T07:00:00",
                    "isDepart": true,
                    "bookingOperatorStatusTypeKey": "confirm",
                    "bookChannel": "web",
                    "mdCountryCodeFrom": null,
                    "mdCountryCodeTo": null,
                    "isCrossCountry": false,
                    "ticketList": [
                        {
                            "goTicketingBookingOperatorTicketStatus": "confirm",
                            "bookingOperatorTicketNo": "GO-Test20231206884C",
                            "operatorTicketNo": "231206EA9C9-MYS",
                            "mdTerminalCodeFrom": "LAR",
                            "mdTerminalNameFrom": "Larkin Sentral",
                            "mdTerminalCodeTo": "MEL",
                            "mdTerminalNameTo": "Melaka Sentral",
                            "routeCode": "WRID",
                            "tripCode": "KLG002",
                            "tripDate": "2023-12-07T00:00:00",
                            "departDate": "2023-12-07T00:00:00",
                            "departDateTime": "2023-12-07T07:00:00",
                            "arriveDateTime": "2023-12-07T20:00:00",
                            "sectionClassTypeName": "Above Deck-STANDARD",
                            "ticketTypeName": "Adult ",
                            "ticketTypePrice": 53.25,
                            "ticketTypeCode": "A",
                            "seatId": "d9793e4e-3701-421c-ac54-b0b3011bdc3e",
                            "seatName": "5D",
                            "seatTypeName": "NORMAL",
                            "seatTypePrice": 0.00,
                            "ticketTypeAddOnTotalPrice": 0.00,
                            "pickCode": "4869fea4-2bb4-460e-815b-afc10039eb3c",
                            "pickName": null,
                            "pickDepartDateTime": "2023-12-07T07:00:00",
                            "dropCode": "",
                            "dropName": "",
                            "platformCharge": 0.00,
                            "ticketTotalPrice": 54.25,
                            "passengerSort": 2,
                            "passengerIdentityName": "Test",
                            "passengerIdentityNo": "123456-13-1231",
                            "passengerIdentityExpiryDate": "0001-01-01T00:00:00",
                            "passengerContactNo": "121212121",
                            "passengerEmail": "",
                            "boardingPassNo": "",
                            "qrWithLogoFilePath": "",
                            "ticketTypeAddOnList": [],
                            "platformAddOnList": [
                                {
                                    "platformAddOnCategoryCode": "Insurance",
                                    "platformAddOnCategoryName": "GoInsure Protection Plan (GPP)",
                                    "platformAddOnName": "GoInsure Protection Plan (GPP)",
                                    "platformAddOnCode": "Insurance",
                                    "platformAddOnPrice": 1.00,
                                    "platformAddOnValue": null,
                                    "platformAddOnItemList": [],
                                    "sort": 1
                                }
                            ]
                        },
                        {
                            "goTicketingBookingOperatorTicketStatus": "confirm",
                            "bookingOperatorTicketNo": "GO-Test20231206FD24",
                            "operatorTicketNo": "231206835BB-MYS",
                            "mdTerminalCodeFrom": "LAR",
                            "mdTerminalNameFrom": "Larkin Sentral",
                            "mdTerminalCodeTo": "MEL",
                            "mdTerminalNameTo": "Melaka Sentral",
                            "routeCode": "WRID",
                            "tripCode": "KLG002",
                            "tripDate": "2023-12-07T00:00:00",
                            "departDate": "2023-12-07T00:00:00",
                            "departDateTime": "2023-12-07T07:00:00",
                            "arriveDateTime": "2023-12-07T20:00:00",
                            "sectionClassTypeName": "Above Deck-STANDARD",
                            "ticketTypeName": "Adult ",
                            "ticketTypePrice": 53.25,
                            "ticketTypeCode": "A",
                            "seatId": "2d971f6d-2c0b-49cb-863b-b0b3011bdc3e",
                            "seatName": "5C",
                            "seatTypeName": "NORMAL",
                            "seatTypePrice": 0.00,
                            "ticketTypeAddOnTotalPrice": 0.00,
                            "pickCode": "4869fea4-2bb4-460e-815b-afc10039eb3c",
                            "pickName": null,
                            "pickDepartDateTime": "2023-12-07T07:00:00",
                            "dropCode": "",
                            "dropName": "",
                            "platformCharge": 0.00,
                            "ticketTotalPrice": 54.25,
                            "passengerSort": 1,
                            "passengerIdentityName": "Keith Wong",
                            "passengerIdentityNo": "910430-01-5169",
                            "passengerIdentityExpiryDate": "0001-01-01T00:00:00",
                            "passengerContactNo": "0103664204",
                            "passengerEmail": "keith.tungwp@gmail.com",
                            "boardingPassNo": "",
                            "qrWithLogoFilePath": "",
                            "ticketTypeAddOnList": [],
                            "platformAddOnList": [
                                {
                                    "platformAddOnCategoryCode": "Insurance",
                                    "platformAddOnCategoryName": "GoInsure Protection Plan (GPP)",
                                    "platformAddOnName": "GoInsure Protection Plan (GPP)",
                                    "platformAddOnCode": "Insurance",
                                    "platformAddOnPrice": 1.00,
                                    "platformAddOnValue": null,
                                    "platformAddOnItemList": [],
                                    "sort": 1
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        "payment": {
            "mdRegionInfoCurrencySymbol": "MYR",
            "totalPrice": 108.50,
            "bookingPaymentStatusTypeKey": "paid",
            "paidOnUtc": "2023-12-06T08:54:24.773",
            "paymentItemList": [
                {
                    "mdRegionInfoCurrencySymbol": "MYR",
                    "totalPrice": 108.50,
                    "paymentMethod": "go_bank",
                    "paymentMethodName": "Go Bank",
                    "paidOnUtc": "2023-12-06T08:54:24.773"
                }
            ]
        },
        "refundPaymentItemList": [],
        "appliedPromotion": null
    }

}