// SEBELUM TUKAR ANY DATA, CHECK DULU CODE SETIAP PRODUCT!

// *DEALS*
export const dataHotel = [
  // { 
  //   id: 1, 
  //   code: "HOTELS-KL00-XXX",
  //   name: "Hotel Test",
  //   link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FHilton-Kuala-Lumpur%2CKuala-Lumpur%2CMalaysia-c4723-h59013-details%2F1rooms%2F2adults", 
  //   image: "https://www.kayak.com.my/rimg/himg/ac/c1/a2/ice-59013-100511407-967033.jpg?width=968&height=607&crop=true",
  //   price: 511,
  //   currency: "MYR",
  //   description: "Located in Kuala Lumpur Sentral, this luxury hotel is within 2 mi (3 km) of Central Market, Merdeka Square and Mid Valley Mega Mall. Kuala Lumpur Tower and Berjaya Times Square are also within 3 mi (5 km). Kuala Lumpur Sentral Station is only a 2-minute walk and KL Sentral Station is 6 minutes.",
  //   // duration: "2 days",
  //   hotel_class: 5,
  //   rating: 8.8,
  //   total_review: "4014", 
  //   tags: ["kl"],
  // },
  { 
    id: 1, 
    code: "HOTELS-KL01-HKL",
    name: "Hilton Kuala Lumpur",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FHilton-Kuala-Lumpur%2CKuala-Lumpur%2CMalaysia-c4723-h59013-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/ac/c1/a2/ice-59013-100511407-967033.jpg?width=968&height=607&crop=true",
    price: 511,
    currency: "MYR",
    description: "Located in Kuala Lumpur Sentral, this luxury hotel is within 2 mi (3 km) of Central Market, Merdeka Square and Mid Valley Mega Mall. Kuala Lumpur Tower and Berjaya Times Square are also within 3 mi (5 km). Kuala Lumpur Sentral Station is only a 2-minute walk and KL Sentral Station is 6 minutes.",
    // duration: "2 days",
    hotel_class: 5,
    rating: 8.8,
    total_review: "4014", 
    tags: ["kl"],
  },
  { 
    id: 2, 
    code: "HOTELS-KL02-PHK",
    name: "Pavilion Hotel Kuala Lumpur Managed By Banyan Tree",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FPavilion-Hotel-Kuala-Lumpur-Managed-By-Banyan-Tree%2CKuala-Lumpur%2CMalaysia-c4723-h901913-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.ar/rimg/himg/87/32/77/ice-901913-111091861-064574.jpg?width=968&height=607&crop=true",
    price: 837,
    currency: "MYR",
    description: "Pavilion Hotel Kuala Lumpur, in the heart of Bukit Bintang, offers 325 tastefully decorated rooms and suites with club facilities for business and leisure travelers who want more personalized services.",
    // duration: "3 hours",
    hotel_class: 5,
    rating: 8.9,
    total_review: "3,205", 
    tags: ["kl"],
  },
  { 
    id: 3, 
    code: "HOTELS-KL03-TMH",
    name: "The Majestic Hotel Kuala Lumpur, Autograph Collection",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FThe-Majestic-Hotel-Kuala-Lumpur%2CAutograph-Collection%2CKuala-Lumpur%2CMalaysia-c4723-h490998-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/ad/9e/e0/sembo-490998-930dfb-465914.jpg?width=968&height=607&crop=true",
    price: 561,
    currency: "MYR",
    description: "Located in Tasik Perdana, this luxury hotel is within a 15-minute walk of National Mosque, Merdeka Square and Petaling Street. Central Market and Kuala Lumpur Bird Park are also within 15 minutes. Kuala Lumpur Station and Kuala Lumpur KTM Komuter Station are within a 5-minute walk",
    // duration: "4 days",
    hotel_class: 5,
    rating: 8.7,
    total_review: "3,525", 
    tags: ["kl"],
  },
  { 
    id: 4, 
    code: "HOTELS-KL04-RCK",
    name: "Royale Chulan Kuala Lumpur",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FRoyale-Chulan-Kuala-Lumpur%2CKuala-Lumpur%2CMalaysia-c4723-h311419-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/1f/f8/66/expediav2-311419-2800ec-932316.jpg?width=968&height=607&crop=true",
    price: 407,
    currency: "MYR",
    description: "Located in Kuala Lumpur City Centre, this luxury hotel is within a 10-minute walk of Starhill Gallery and Pavilion Kuala Lumpur. KLCC Park and Kuala Lumpur Convention Centre are also within 15 minutes. Raja Chulan Station is 9 minutes by foot and Bukit Bintang Station is 13 minutes",
    // duration: "1 hours",
    hotel_class: 5,
    rating: 8.2,
    total_review: "2,677", 
    tags: ["kl"],
  },
  { 
    id: 5, 
    code: "HOTELS-KL05-SIK",
    name: "Sheraton Imperial Kuala Lumpur Hotel",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FSheraton-Imperial-Kuala-Lumpur-Hotel%2CKuala-Lumpur%2CMalaysia-c4723-h35047-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/b2/13/a3/leonardo-125230336-kulsi-cochere-9893-hor-clsc_O-037218.jpg?width=968&height=607&crop=true",
    price: 461,
    currency: "MYR",
    description: "Located in Kuala Lumpur City Centre, this luxury hotel is within a 15-minute walk of Maju Junction Mall, SOGO and Masjid India. Merdeka Square and Petronas Twin Towers are also within 1 mile (2 km). Medan Tuanku Station is only a 2-minute walk and Bukit Nanas Station is 9 minutes.",
    // duration: "2 days",
    hotel_class: 5,
    rating: 8.4,
    total_review: "2,732", 
    tags: ["kl"],
  },
  { 
    id: 6, 
    code: "HOTELS-KL06-IKL",
    name: "Intercontinental Kuala Lumpur",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FIntercontinental-Kuala-Lumpur%2CKuala-Lumpur%2CMalaysia-c4723-h382183-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/ea/c4/10/leonardo-1240790-KULHA_4047009413_O-421900.jpg?width=968&height=607&crop=true",
    price: 486,
    currency: "MYR",
    description: "This family-friendly Kuala Lumpur hotel is located in the business district, within a 15-minute walk of Ampang Park, Petronas Twin Towers and Suria KLCC Shopping Centre. KLCC Park and Royal Thai Embassy are also within 15 minutes. Ampang Park Station is only a 5-minute walk and KLCC Station is 7 minutes.",
    // duration: "",
    hotel_class: 5,
    rating: 8.7,
    total_review: "3,053", 
    tags: ["kl"],
  },
  { 
    id: 7, 
    code: "HOTELS-KL07-LMK",
    name: "Le Méridien Kuala Lumpur",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FLe-M%C3%A9ridien-Kuala-Lumpur%2CKuala-Lumpur%2CMalaysia-c4723-h45588-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/89/56/7e/leonardo-45588-157272159-995430.jpg?width=968&height=607&crop=true",
    price: 472,
    currency: "MYR",
    description: "Located in Kuala Lumpur Sentral, this luxury hotel is within a 10-minute walk of NU Sentral and Kuala Lumpur Sentral. Kuala Lumpur Bird Park and Lake Gardens are also within 1 mile (2 km). Kuala Lumpur Sentral Station is only a 2-minute walk and KL Sentral Station is 6 minutes.",
    // duration: "",
    hotel_class: 5,
    rating: 8.8,
    total_review: "2,253", 
    tags: ["kl"],
  },
  { 
    id: 8, 
    code: "HOTELS-KL08-SSH",
    name: "Sama-Sama Hotel, KLIA",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FSama-Sama-Hotel%2CKLIA%2CSepang%2CMalaysia-c48542-h170377-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/06/6b/60/ice-113539-73907837_3XL-338701.jpg?width=968&height=607&crop=true",
    price: 729,
    currency: "MYR",
    description: "Situated in Sepang, this luxury hotel is within 6 miles (10 km) of KLIA Jungle Boardwalk, Bukit Lanjut and Sultan Abdul Samad Mosque. Mitsui Outlet Park Klia Sepang and National Automobile Museum are also within 9 miles (15 km). Kuala Lumpur International Airport Station is 20 minutes by foot.",
    // duration: "",
    hotel_class: 5,
    rating: 8.9,
    total_review: "6,583", 
    tags: ["kl"],
  },
  { 
    id: 9, 
    code: "HOTELS-KL09-GMH",
    name: "Grand Millennium Hotel Kuala Lumpur",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FGrand-Millennium-Hotel-Kuala-Lumpur%2CKuala-Lumpur%2CMalaysia-c4723-h35043-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/b6/76/d0/expediav2-35043-d995ec-609676.jpg?width=968&height=607&crop=true",
    price: 426,
    currency: "MYR",
    description: "Located in Kuala Lumpur City Centre, this luxury hotel is steps away from Pavilion Kuala Lumpur and Lot 10 Shopping Centre. Jalan Alor and Aquaria KLCC are also within 10 minutes. Bukit Bintang Station is only a 4-minute walk and Raja Chulan Station is 8 minutes.",
    // duration: "2 days",
    hotel_class: 5,
    rating: 8.3,
    total_review: "6,282", 
    tags: ["kl"],
  },
  { 
    id: 10, 
    code: "HOTELS-KL10-JMH",
    name: "JW Marriott Hotel Kuala Lumpur",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FJW-Marriott-Hotel-Kuala-Lumpur%2CKuala-Lumpur%2CMalaysia-c4723-h59016-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/ba/7b/8d/leonardo-59016-165689363-966958.jpg?width=968&height=607&crop=true",
    price: 505,
    currency: "MYR",
    description: "Located in Kuala Lumpur City Centre, this luxury hotel is steps away from Fahrenheit 88 Shopping Mall and Pavilion Kuala Lumpur. Lot 10 Shopping Centre and Bukit Bintang Plaza are also within 10 minutes. Bukit Bintang Station is 5 minutes by foot and Raja Chulan Station is 9 minutes.",
    // duration: "",
    hotel_class: 5,
    rating: 8.7,
    total_review: "5,125", 
    tags: ["kl"],
  },
  { 
    id: 11, 
    code: "HOTELS-KL11-RKL",
    name: "Renaissance Kuala Lumpur Hotel & Convention Centre",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FRenaissance-Kuala-Lumpur-Hotel-Convention-Centre%2CKuala-Lumpur%2CMalaysia-c4723-h19872-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/af/8d/69/leonardo-19872-167901247-314834.jpg?width=968&height=607&crop=true",
    price: 742,
    currency: "MYR",
    description: "Located in Kuala Lumpur City Centre, this luxury hotel is within a 15-minute walk of Kuala Lumpur Forest Eco Park and Petronas Twin Towers. KLCC Park and Kuala Lumpur Tower are also within 1 mi (2 km). Bukit Nanas Station is only a 2-minute walk and Dang Wangi Station is 3 minutes.",
    // duration: "",
    hotel_class: 5,
    rating: 8.1,
    total_review: "38", 
    tags: ["kl"],
  },
  { 
    id: 12, 
    code: "HOTELS-KL12-HSK",
    name: "Hotel Stripes Kuala Lumpur, Autograph Collection",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FHotel-Stripes-Kuala-Lumpur%2CAutograph-Collection%2CKuala-Lumpur%2CMalaysia-c4723-h2677338-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/39/22/0f/leonardo-2035620-kulsp-brasserie-0018-hor-clsc_O-666207.jpg?width=968&height=607&crop=true",
    price: 425,
    currency: "MYR",
    description: "Located in Kuala Lumpur City Centre, this luxury hotel is within a 10-minute walk of Maju Junction Mall and SOGO. Merdeka Square and Petronas Twin Towers are also within 1 mile (2 km). Medan Tuanku Station is only a 4-minute walk and Dang Wangi Station is 6 minutes.",
    // duration: "",
    hotel_class: 5,
    rating: 8.7,
    total_review: "1,896", 
    tags: ["kl"],
  },
  { 
    id: 13, 
    code: "HOTELS-KL13-TWK",
    name: "The Westin Kuala Lumpur",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FThe-Westin-Kuala-Lumpur%2CKuala-Lumpur%2CMalaysia-c4723-h40026-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/23/26/b1/leonardo-40026-167848233-764352.jpg?width=968&height=607&crop=true",
    price: 562,
    currency: "MYR",
    description: "Located in Kuala Lumpur City Centre, this luxury hotel is steps away from Starhill Gallery and Pavilion Kuala Lumpur. Lot 10 Shopping Centre and Bukit Bintang Plaza are also within 10 minutes. Bukit Bintang Station is 7 minutes by foot and Raja Chulan Station is 10 minutes.",
    // duration: "",
    hotel_class: 5,
    rating: 8.6,
    total_review: "2,011", 
    tags: ["kl"],
  },
  { 
    id: 14, 
    code: "HOTELS-KL14-QSK",
    name: "Quill Suites Klcc",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FQuill-Suites-Klcc%2CKuala-Lumpur%2CMalaysia-c4723-h10324379-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/96/ba/f7/booking-10324379-500527708-805948.jpg?width=968&height=607&crop=true",
    price: 270,
    currency: "MYR",
    description: "Set in Kuala Lumpur, 1.7 km from Petronas Twin Towers, Quill Suites KLCC offers accommodation with an outdoor swimming pool, free private parking, a garden and a bar. Each accommodation at the 5-star hotel has city views, and guests can enjoy access to a children's playground and to a hammam. The accommodation provides a 24-hour front desk, airport transfers, an ATM and free WiFi throughout the property. The hotel will provide guests with air-conditioned rooms offering a desk, a kettle, a fridge, an oven, a safety deposit box, a flat-screen TV, a balcony and a private bathroom with a bidet. At Quill Suites KLCC all rooms have bed linen and towels. At the accommodation you will find a restaurant serving American, Argentinian and Brazilian cuisine. Vegetarian, halal and vegan options can also be requested. Quill Suites KLCC offers a barbecue. Popular points of interest near the hotel include Suria KLCC, Putra World Trade Centre and Bank Negara Malaysia Museum and Art Gallery. The nearest airport is Sultan Abdul Aziz Shah Airport, 23 km from Quill Suites KLCC.",
    // duration: "",
    hotel_class: 5,
    rating: 8.9,
    total_review: "74", 
    tags: ["kl"],
  },
  { 
    id: 15, 
    code: "HOTELS-KL15-DTH",
    name: "DoubleTree by Hilton Kuala Lumpur",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FDoubleTree-by-Hilton-Kuala-Lumpur%2CKuala-Lumpur%2CMalaysia-c4723-h333407-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/90/19/a2/ice-333407-100511212-729042.jpg?width=968&height=607&crop=true",
    price: 365,
    currency: "MYR",
    description: "This family-friendly Kuala Lumpur hotel is located in the entertainment district, within a 15-minute walk of Ampang Park and Royal Thai Embassy. Petronas Twin Towers and Suria KLCC Shopping Centre are also within 1 mile (2 km). Ampang Park Station is 8 minutes by foot and KLCC Station is 14 minutes.",
    // duration: "",
    hotel_class: 5,
    rating: 8.5,
    total_review: "5,290", 
    tags: ["kl"],
  },
  { 
    id: 16, 
    code: "HOTELS-KL16-ASK",
    name: "Axquisite Suites At Klcc",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FAxquisite-Suites-At-Klcc%2CKuala-Lumpur%2CMalaysia-c4723-h1070728388-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/d0/fa/86/expediav2-1070728388-7d39e5-060610.jpg?width=968&height=607&crop=true",
    price: 511,
    currency: "MYR",
    description: "Located in Kuala Lumpur, 700 metres from Petronas Twin Towers, The Five Star Escapes at KLCC provides accommodation with an outdoor swimming pool, private parking, a fitness centre and a garden. Providing a restaurant, the property also has a bar, as well as a sauna and a hot tub. The property is 800 metres from Suria KLCC, and within 1.3 km of the city centre. All units in the hotel are equipped with air conditioning, a seating area, a flat-screen TV with cable channels, a kitchen, a dining area and a private bathroom with free toiletries, a shower and a hot tub. At The Five Star Escapes at KLCC every room is equipped with bed linen and towels. The accommodation offers a sun terrace. Staff speak Arabic, English, Hausa and Indonesian at the reception. Popular points of interest near The Five Star Escapes at KLCC include Kuala Lumpur Convention Center, KLCC Park and Pavilion Kuala Lumpur. The nearest airport is Sultan Abdul Aziz Shah, 24 km from the hotel, and the property offers a paid airport shuttle service.",
    // duration: "",
    hotel_class: 5,
    rating: 8.7,
    total_review: "120", 
    tags: ["kl"],
  },
  { 
    id: 17, 
    code: "HOTELS-KL17-TRC",
    name: "The Ritz-Carlton Kuala Lumpur",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FThe-Ritz-Carlton-Kuala-Lumpur%2CKuala-Lumpur%2CMalaysia-c4723-h11483-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/2b/1d/e6/leonardo-1073586-kulrz-deluxe-0007-hor-clsc_O-225071.jpg?width=968&height=607&crop=true",
    price: 655,
    currency: "MYR",
    description: "Located in Golden Triangle, this luxury hotel is within a 10-minute walk of Starhill Gallery, Pavilion Kuala Lumpur, and Berjaya Times Square. Lot 10 Shopping Centre and Prince Court Medical Centre are also within 15 minutes. Bukit Bintang Station is 8 minutes by foot and Imbi Station is 10 minutes.",
    // duration: "",
    hotel_class: 5,
    rating: 8.6,
    total_review: "1,673", 
    tags: ["kl"],
  },
  { 
    id: 18, 
    code: "HOTELS-KL18-PPS",
    name: "Pan Pacific Serviced Suites Kuala Lumpur",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FPan-Pacific-Serviced-Suites-Kuala-Lumpur%2CKuala-Lumpur%2CMalaysia-c4723-h1070564420-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/b2/8d/e8/ice-1070564420-101638384-146608.jpg?width=968&height=607&crop=true",
    price: 557,
    currency: "MYR",
    description: "Situated 500 metres from Berjaya Times Square, Pan Pacific Serviced Suites Kuala Lumpur features accommodation with an outdoor swimming pool, a shared lounge and a 24-hour front desk for your convenience. Complimentary WiFi is available throughout the property and private parking is available on site. Accommodation is fitted with air conditioning, a fully equipped kitchenette with a dining area, a flat-screen TV and a private bathroom with bidet, a hairdryer and free toiletries. A fridge and stovetop are also featured, as well as a kettle. The aparthotel offers a sun terrace. Popular points of interest near Pan Pacific Serviced Suites Kuala Lumpur include Starhill Gallery, Pavilion Kuala Lumpur and Kuala Lumpur Convention Center. The nearest airport is Sultan Abdul Aziz Shah Airport, 31 km from the accommodation.",
    // duration: "",
    hotel_class: 5,
    rating: 9,
    total_review: "783", 
    tags: ["kl"],
  },
  { 
    id: 19, 
    code: "HOTELS-KL19-SLK",
    name: "Shangri-La Kuala Lumpur",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FShangri-La-Kuala-Lumpur%2CKuala-Lumpur%2CMalaysia-c4723-h35041-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/35/c5/5e/ice-73953-0757184_3XL-239347.jpg?width=968&height=607&crop=true",
    price: 552,
    currency: "MYR",
    description: "This family-friendly Kuala Lumpur hotel is located in the entertainment district, within a 15-minute walk of Kuala Lumpur Tower, KLCC Park and Kuala Lumpur Convention Centre. Petronas Twin Towers and Suria KLCC Shopping Centre are also within 15 minutes. Bukit Nanas Station is only a 5-minute walk and Dang Wangi Station is 7 minutes.",
    // duration: "",
    hotel_class: 5,
    rating: 8.8,
    total_review: "2,673", 
    tags: ["kl"],
  },
  { 
    id: 20, 
    code: "HOTELS-KL20-GHK",
    name: "Grand Hyatt Kuala Lumpur",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FGrand-Hyatt-Kuala-Lumpur%2CKuala-Lumpur%2CMalaysia-c4723-h676150-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/29/c5/7f/ice-87537206-70564552_3XL-560152.jpg?width=968&height=607&crop=true",
    price: 724,
    currency: "MYR",
    description: "This family-friendly Kuala Lumpur hotel is located in the shopping district, within a 10-minute walk of Kuala Lumpur Convention Centre, Petronas Twin Towers and Pavilion Kuala Lumpur. Kuala Lumpur Tower and Central Market are also within 2 mi (3 km). Raja Chulan Station is 8 minutes by foot and KLCC Station is 11 minutes.",
    // duration: "",
    hotel_class: 5,
    rating: 9,
    total_review: "3,615", 
    tags: ["kl"],
  },
  { 
    id: 21, 
    code: "HOTELS-MEL21-DTH",
    name: "DoubleTree by Hilton Melaka",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FDoubleTree-by-Hilton-Melaka%2CMalacca%2CMalaysia-c19573-h2905827-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/08/26/1a/expediav2-2905827-05bc0f-213186.jpg?width=968&height=607&crop=true",
    price: 410,
    currency: "MYR",
    description: "Located in the heart of Malacca City, this luxury hotel is within 1 mile (2 km) of Portuguese Settlement, Hatten Square and Dataran Pahlawan Melaka Megamall. Mahkota Medical Center and A Famosa are also within 1 mile (2 km).",
    // duration: "",
    hotel_class: 5,
    rating: 8.5,
    total_review: "3,020", 
    tags: ["melaka"],
  },
  { 
    id: 22, 
    code: "HOTELS-MEL22-CDR",
    name: "Casa Del Rio Melaka",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FCasa-Del-Rio-Melaka%2CMalacca%2CMalaysia-c19573-h344346-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/29/92/d3/sembo-344346-b919cb-792415.jpg?width=968&height=607&crop=true",
    price: 991,
    currency: "MYR",
    description: "Located in Taman Kota Laksamana, this luxury hotel is within a 10-minute walk of Baba Nyonya Heritage Museum and Jonker Street Night Market. A Famosa and Mahkota Parade Shopping Mall are also within 1 mile (2 km).",
    // duration: "",
    hotel_class: 5,
    rating: 9.2,
    total_review: "352", 
    tags: ["melaka"],
  },
  { 
    id: 23, 
    code: "HOTELS-MEL23-CMM",
    name: "Courtyard by Marriott Melaka",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FCourtyard-by-Marriott-Melaka%2CMalacca%2CMalaysia-c19573-h1070710578-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/83/03/d0/leonardo-1070710578-156802615-404456.jpg?width=968&height=607&crop=true",
    price: 391,
    currency: "MYR",
    description: "At Courtyard Melaka, you can turn new experiences into lasting memories. Courtyard Melaka is located in the historic city of Melaka close to St. Peter's Church and minutes from Stadthuys, A Formosa fort, and the traditional Malay village at Kampung Morten. With a contemporary design guest room, warm hospitality, our city center hotel helps you feel welcome and settled in Melaka. Host flawless conferences, events and wedding celebrations in our flexible grand ballroom and meeting spaces. Fuel up in the morning at Courtyard Cafe and return in the evening for tasty cocktails at our 1939 Lounge. Our fitness center is equipped with treadmills, ellipticals, exercise bikes, and free weights, or dip into our infinity pool overlooking the city and the Straits of Malacca. Our Melaka hotel rooms and suites include complimentary high speed Wi-Fi, 55-inch HDTV, rain showers, slippers, kettles and work desks. Whether traveling for business or pleasure, Courtyard Melaka helps you achieve more.",
    // duration: "",
    hotel_class: 4,
    rating: 8.7,
    total_review: "404", 
    tags: ["melaka"],
  },
  { 
    id: 24, 
    code: "HOTELS-MEL24-DSF",
    name: "D savoy @ Famosa by MR",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FD-savoy-Famosa-by-MR%2CTampin%2CMalaysia-c312237-h4763734-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/4f/a1/84/booking-4763734-173674448-576762.jpg?width=968&height=607&crop=true",
    price: 253,
    currency: "MYR",
    description: "Located within 34 km of Cheng Hoon Teng Temple and 35 km of Baba & Nyonya Heritage Museum, D savoy @ Famosa by MR provides rooms in Melaka. Featuring a restaurant, the 4-star hotel has air-conditioned rooms with a private bathroom. Menara Taming Sari is 36 km from the hotel and Porta de Santiago is 37 km away. At the hotel, every room has a balcony. Straits Chinese Jewelry Museum Malacca is 35 km from D savoy @ Famosa by MR, while The Stadthuys is 36 km away. The nearest airport is Melaka International Airport, 36 km from the accommodation.",
    // duration: "",
    hotel_class: 4,
    rating: 8.5,
    total_review: "40", 
    tags: ["melaka"],
  },
  { 
    id: 25, 
    code: "HOTELS-MEL25-IBM",
    name: "ibis Melaka",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2Fibis-Melaka%2CMalacca%2CMalaysia-c19573-h2985664-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/6d/db/59/ice-123246222-69538151_3XL-345186.jpg?width=968&height=607&crop=true",
    price: 286,
    currency: "MYR",
    description: "Located in the heart of Malacca City, this hotel is within a 10-minute walk of Putra Specialist Hospital and The Shore Oceanarium. Red Square and Christ Church are also within 15 minutes.",
    // duration: "",
    hotel_class: 4,
    rating: 8.2,
    total_review: "5,149", 
    tags: ["melaka"],
  },
  { 
    id: 26, 
    code: "HOTELS-MEL26-TPM",
    name: "The Pines Melaka",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FThe-Pines-Melaka%2CMalacca%2CMalaysia-c19573-h2349380-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/4d/ab/35/expediav2-2349380-0e3d28-148599.jpg?width=968&height=607&crop=true",
    price: 451,
    currency: "MYR",
    description: "This family-friendly Malacca City hotel is located on the riverwalk, within 1 mi (2 km) of St. Peter's Church Melaka, Jonker Street Night Market and A Famosa. Mahkota Parade Shopping Mall and Dataran Pahlawan Melaka Megamall are also within 2 miles (3 km).",
    // duration: "",
    hotel_class: 4,
    rating: 8.2,
    total_review: "3,544", 
    tags: ["melaka"],
  },
  { 
    id: 27, 
    code: "HOTELS-MEL27-MHL",
    name: "Moty Hotel",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FMoty-Hotel%2CMalacca%2CMalaysia-c19573-h2903236-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/0b/28/f4/expediav2-2903236-38048a-203936.jpg?width=968&height=607&crop=true",
    price: 109,
    currency: "MYR",
    description: "Situated in Malacca City, this hotel is within a 10-minute walk of Maritime Museum Muzium Samudera, Mahkota Medical Center and Mahkota Parade Shopping Mall. Dataran Pahlawan Melaka Megamall and A Famosa are also within 10 minutes.",
    // duration: "",
    hotel_class: 4,
    rating: 8.5,
    total_review: "2,927", 
    tags: ["melaka"],
  },
  { 
    id: 28, 
    code: "HOTELS-MEL28-RMC",
    name: "Rosa Malacca",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FRosa-Malacca%2CMalacca%2CMalaysia-c19573-h2691689-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/f1/2a/6d/expediav2-2691689-aa4728-433344.jpg?width=968&height=607&crop=true",
    price: 412,
    currency: "MYR",
    description: "Located in the heart of Malacca City, this hotel is within a 15-minute walk of Hatten Square, A Famosa and Dataran Pahlawan Melaka Megamall. Mahkota Medical Center and Mahkota Parade Shopping Mall are also within 15 minutes.",
    // duration: "",
    hotel_class: 4,
    rating: 8.8,
    total_review: "1,877", 
    tags: ["melaka"],
  },
  { 
    id: 29, 
    code: "HOTELS-MEL29-THS",
    name: "Treasures Hotel and Suites",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FTreasures-Hotel-and-Suites%2CMalacca%2CMalaysia-c19573-h3542746-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/kimg/16/85/3b78e05d-5be17493-62.jpg?width=968&height=607&crop=true",
    price: 591,
    currency: "MYR",
    description: "Situated in Malacca City, this hotel is within a 15-minute walk of Jonker Street Night Market and A Famosa. Mahkota Parade Shopping Mall and Dataran Pahlawan Melaka Megamall are also within 1 mi (2 km).",
    // duration: "",
    hotel_class: 4,
    rating: 8.4,
    total_review: "1,112", 
    tags: ["melaka"],
  },
  { 
    id: 30, 
    code: "HOTELS-MEL30-TSH",
    name: "The Settlement Hotel",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FThe-Settlement-Hotel%2CMalacca%2CMalaysia-c19573-h742215-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/c1/a9/54/revato-611225-12478164-997739.jpg?width=968&height=607&crop=true",
    price: 293,
    currency: "MYR",
    description: "Located in the heart of Malacca City, this spa hotel is within 1 mile (2 km) of Portuguese Settlement and Hatten Square. A Famosa and Dataran Pahlawan Melaka Megamall are also within 2 miles (3 km).",
    // duration: "",
    hotel_class: 4,
    rating: 8.5,
    total_review: "1,362", 
    tags: ["melaka"],
  },
  { 
    id: 31, 
    code: "HOTELS-MEL31-TAP",
    name: "The Apple Premier Suites Melaka",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FThe-Apple-Premier-Suites-Melaka%2CMalacca%2CMalaysia-c19573-h9319467-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/85/4a/68/booking-9319467-386090868-565445.jpg?width=968&height=607&crop=true",
    price: 443,
    currency: "MYR",
    description: "Boasting a year-round outdoor pool, The Apple Premier Suites Melaka in Melaka offers accommodation with free WiFi and free private parking for guests who drive. Accommodation is fitted with air conditioning, a fully equipped kitchen with a dining area, a flat-screen TV and a private bathroom with bidet, free toiletries and a hairdryer. A fridge and microwave are also offered, as well as a kettle. The apartment offers a fitness centre. A children's playground is available for guests to use at The Apple Premier Suites Melaka. Popular points of interest near the accommodation include The Stadthuys, Baba & Nyonya Heritage Museum and Straits Chinese Jewelry Museum Malacca. The nearest airport is Melaka International Airport, 6 km from The Apple Premier Suites Melaka.",
    // duration: "",
    hotel_class: 4,
    rating: 8.3,
    total_review: "912", 
    tags: ["melaka"],
  },
  { 
    id: 32, 
    code: "HOTELS-MEL32-CHB",
    name: "Courtyard At Heeren Boutique Hotel",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FCourtyard-At-Heeren-Boutique-Hotel%2CMalacca%2CMalaysia-c19573-h2394802-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/9e/05/fc/expediav2-2394802-98642c-634201.jpg?width=968&height=607&crop=true",
    price: 426,
    currency: "MYR",
    description: "Located in Taman Kota Laksamana, this boutique hotel is steps away from Straits Chinese Jewelry Museum Malacca and Jonker Street Night Market. A Famosa and Mahkota Parade Shopping Mall are also within 15 minutes.",
    // duration: "",
    hotel_class: 3,
    rating: 8.6,
    total_review: "117", 
    tags: ["melaka"],
  },
  { 
    id: 33, 
    code: "HOTELS-MEL33-GSB",
    name: "Grand Swiss-Belhotel Melaka (formerly LaCrista Hotel Melaka)",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FGrand-Swiss-Belhotel-Melaka-formerly-LaCrista-Hotel-Melaka-%2CMalacca%2CMalaysia-c19573-h118943-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/7d/6c/6d/revato-118943-38009062-427479.jpg?width=968&height=607&crop=true",
    price: 333,
    currency: "MYR",
    description: "Located in the heart of Malacca City, this hotel is within a 15-minute walk of Kampung Hulu Mosque and Jonker Street Night Market. A Famosa and Mahkota Parade Shopping Mall are also within 2 miles (3 km).",
    // duration: "",
    hotel_class: 3,
    rating: 8.5,
    total_review: "1,378", 
    tags: ["melaka"],
  },
  { 
    id: 34, 
    code: "HOTELS-MEL34-QSH",
    name: "Quayside Hotel",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FQuayside-Hotel%2CMalacca%2CMalaysia-c19573-h576202-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/03/5b/ca/revato-624082-11197401-855791.jpg?width=968&height=607&crop=true",
    price: 265,
    currency: "MYR",
    description: "Located in Bandar Hilir, this hotel is within a 5-minute walk of Maritime Museum Muzium Samudera and Jonker Street Night Market. A Famosa and Mahkota Parade Shopping Mall are also within 10 minutes.",
    // duration: "",
    hotel_class: 3,
    rating: 8.3,
    total_review: "220", 
    tags: ["melaka"],
  },
  { 
    id: 35, 
    code: "HOTELS-MEL35-TBH",
    name: "Theblanc Boutique Hotel",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FTheblanc-Boutique-Hotel%2CMalacca%2CMalaysia-c19573-h2923755-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.ar/rimg/himg/ca/5b/c2/expediav2-2923755-115915-981016.jpg?width=968&height=607&crop=true",
    price: 279,
    currency: "MYR",
    description: "The Blanc Boutique Hotel offers air-conditioned rooms with free WiFi throughout the property in a restored 3-storey listed building on Jonker Street. The rooms have a flat-screen cable TV, a kettle and a private bathroom with a bath or shower, a bidet, a hairdryer and free toiletries. There is a 24-hour reception. Sam Po Kong Temple is 1.2 km from The Blanc Boutique Hotel and Melaka Sentral is 2.6 km away. Kuala Lumpur International Airport is 86 km away.",
    // duration: "",
    hotel_class: 3,
    rating: 8.9,
    total_review: "574", 
    tags: ["melaka"],
  },
  { 
    id: 36, 
    code: "HOTELS-MEL36-SCH",
    name: "Seri Costa Hotel",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FSeri-Costa-Hotel%2CMalacca%2CMalaysia-c19573-h141878-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/52/3d/38/expediav2-141878-e601e4-651236.jpg?width=968&height=607&crop=true",
    price: 157,
    currency: "MYR",
    description: "Situated in Malacca City, this hotel is within a 10-minute walk of Maritime Museum Muzium Samudera, Mahkota Parade Shopping Mall and Dataran Pahlawan Melaka Megamall. A Famosa and Mahkota Medical Center are also within 10 minutes.",
    // duration: "",
    hotel_class: 3,
    rating: 8.3,
    total_review: "328", 
    tags: ["melaka"],
  },
  { 
    id: 37, 
    code: "HOTELS-MEL37-JHH",
    name: "Jonkered Heritage Hotel",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FJonkered-Heritage-Hotel%2CMalacca%2CMalaysia-c19573-h5956507-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/b5/a3/98/expediav2-5956507-1916927850-454355.jpg?width=968&height=607&crop=true",
    price: 416,
    currency: "MYR",
    description: "Along with self parking, this smoke-free hotel has a 24-hour front desk and tour/ticket assistance. WiFi in public areas is free. Additionally, multilingual staff, a convenience store, and a front-desk safe are onsite. All 25 individually decorated rooms feature free WiFi and room service. For a bit of entertainment, guests will have flat-screen TVs with cable channels, and other amenities include free bottled water and safes.",
    // duration: "",
    hotel_class: 3,
    rating: 8.5,
    total_review: "1,691", 
    tags: ["melaka"],
  },
  { 
    id: 38, 
    code: "HOTELS-MEL38-SIA",
    name: "Siantan - Near Std Hang Jebat, Sg Udang & Uitm Lendu",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FSiantan%2CNear-Std-Hang-Jebat%2CSg-Udang-Uitm-Lendu%2CMalacca%2CMalaysia-c19573-h2872117-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/ad/cf/30/booking-2036000-110222294-image.jpg?width=968&height=607&crop=true",
    price: 495,
    currency: "MYR",
    description: "Siantan - Near Std Hang Jebat, Sg Udang & UITM Lendu is conveniently located in Jalan Siantan, just 10 km from Melaka Sentral and within a 20-minute drive to the city centre. The bungalow is located in a gated & guarded area. Master bedroom & 2nd room are equipped with queen size bed, 3rd room with 2 single beds & the 4th room with 1 super single bed + 1 bunk bed thus can accommodate a total of 9 pax comfortably. For your extra comfort aircon are fitted in all the rooms. The 2 bathrooms are fitted with water heater & shower facility. The vacation home comes with a large seating area. Plenty of natural light comes through the door-sized windows & sliding door. Thus ventilation is good. WIFI 30mbps powered by Unifi is free for our guests. Provided in the vacation home is 40 inch SMART TV for guests to watch online UHD movies by Netflix, YouTube Premium & browse internet etc. Satellite TV channel ASTRO is also provided. The tourist attraction sites in Melaka are located in 3 main areas; Banda Hilir, Ayer Keroh and Alor Gajah. This bungalow is in the middle of the areas; within 5-20km distant to any of them. It is next to the main road thus guarantees easy access to all 3 areas. For our guests we will provide you with Travel Itinerary & E-Books comprising of Tourist Attraction Sites & Famous Food Outlets as reference, segregated based on the 3 areas mentioned earlier. This will help in your planning.",
    // duration: "",
    hotel_class: 3,
    rating: 9.4,
    total_review: "21", 
    tags: ["melaka"],
  },
  { 
    id: 39, 
    code: "HOTELS-MEL39-MBH",
    name: "Mercury Boutique Hotel",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FMercury-Boutique-Hotel%2CMalacca%2CMalaysia-c19573-h2363957-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/f7/a4/27/expediav2-2363957-2189663271-231081.jpg?width=968&height=607&crop=true",
    price: 132,
    currency: "MYR",
    description: "Located in the heart of Malacca City, this hotel is within a 10-minute walk of Maritime Museum Muzium Samudera, Mahkota Medical Center and Mahkota Parade Shopping Mall. Dataran Pahlawan Melaka Megamall and A Famosa are also within 10 minutes.",
    // duration: "",
    hotel_class: 3,
    rating: 8.3,
    total_review: "1,196", 
    tags: ["melaka"],
  },
  { 
    id: 40, 
    code: "HOTELS-MEL40-STH",
    name: "Styles Hotel",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FStyles-Hotel%2CMalacca%2CMalaysia-c19573-h3619770-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/d9/a9/03/expediav2-3619770-72bdf1-674490.jpg?width=968&height=607&crop=true",
    price: 312,
    currency: "MYR",
    description: "Located in Jonker Walk, this hotel is steps away from Malacca Heritage Centre and Jonker Street Night Market. A Famosa and Mahkota Parade Shopping Mall are also within 15 minutes.",
    // duration: "",
    hotel_class: 3,
    rating: 8.2,
    total_review: "110", 
    tags: ["melaka"],
  },
  { 
    id: 41, 
    code: "HOTELS-MEL41-LHP",
    name: "The Light Hotel Penang",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FThe-Light-Hotel-Penang%2CButterworth%2CMalaysia-c3197-h2270161-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/09/16/8a/expediav2-2270161-299ac7-583840.jpg?width=968&height=607&crop=true",
    price: 426,
    currency: "MYR",
    description: "Located in Central Seberang Perai, this luxury hotel is within a 10-minute walk of Penang Bird Park and Sunway Carnival Mall. Sultan Abdul Halim Ferry Terminal and Ninth Emperor God Temple are also within 6 mi (10 km).",
    // duration: "",
    hotel_class: 5,
    rating: 8.9,
    total_review: "1,189", 
    tags: ["penang"],
  },
  { 
    id: 42, 
    code: "HOTELS-MEL42-GHK",
    name: "G Hotel Kelawai",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FG-Hotel-Kelawai%2CGeorge-Town%2CMalaysia-c4178-h800108-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/0d/5f/72/expediav2-800108-eb7717-177514.jpg?width=968&height=607&crop=true",
    price: 536,
    currency: "MYR",
    description: "Located in Downtown George Town, this luxury hotel is within a 10-minute walk of Gurney Plaza, Gurney Drive, and Penang Adventist Hospital. Gleneagles Penang Medical Centre and Loh guan Lye Specialist Centre are also within 2 miles (3 km).",
    // duration: "",
    hotel_class: 5,
    rating: 8.6,
    total_review: "800", 
    tags: ["penang"],
  },
  { 
    id: 43, 
    code: "HOTELS-MEL43-GHG",
    name: "G Hotel Gurney",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FG-Hotel-Gurney%2CGeorge-Town%2CMalaysia-c4178-h202435-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/52/08/0e/expediav2-202435-ee0c7d-618339.jpg?width=968&height=607&crop=true",
    price: 683,
    currency: "MYR",
    description: "Located in Downtown George Town, this luxury hotel is within a 5-minute walk of Gurney Drive and Gurney Plaza. Penang Adventist Hospital and Gleneagles Penang Medical Centre are also within 1 mile (2 km).",
    // duration: "",
    hotel_class: 5,
    rating: 8.6,
    total_review: "958", 
    tags: ["penang"],
  },
  { 
    id: 44, 
    code: "HOTELS-MEL44-EOH",
    name: "Eastern & Oriental Hotel",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FEastern-Oriental-Hotel%2CGeorge-Town%2CMalaysia-c4178-h20806-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/b3/cb/e0/expediav2-20806-6febdd-792402.jpg?width=968&height=607&crop=true",
    price: 935,
    currency: "MYR",
    description: "This family-friendly George Town hotel is located on the waterfront, within a 15-minute walk of Cheong Fatt Tze Mansion and Penang City Hall. KOMTAR and Penang Times Square are also within 1 mile (2 km).",
    // duration: "",
    hotel_class: 5,
    rating: 8.8,
    total_review: "3,457", 
    tags: ["penang"],
  },
  { 
    id: 45, 
    code: "HOTELS-MEL45-USG",
    name: "Urban Suite - George Town",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FUrban-Suite%2CGeorge-Town%2CJelutong%2CMalaysia-c92383-h10277190-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/ec/6f/fe/booking-10277190-497165054-555246.jpg?width=968&height=607&crop=true",
    price: 545,
    currency: "MYR",
    description: "Situated in Jelutong, 4.1 km from 1st Avenue Penang, Urban Suite - George Town features accommodation with an outdoor swimming pool, free private parking, a garden and a terrace. With free WiFi, this 5-star hotel offers a 24-hour front desk and a business centre. The property is allergy-free and is set 4.3 km from Penang Times Square. The rooms in the hotel are fitted with air conditioning, a seating area, a flat-screen TV with satellite channels, a kitchen, a dining area and a private bathroom with a hairdryer, a bidet and a shower. Urban Suite - George Town offers some rooms with sea views, and all rooms are fitted with a kettle. At the accommodation rooms have bed linen and towels. Rainbow Skywalk at Komtar is 4.7 km from Urban Suite - George Town, while Wonderfood Museum is 5.4 km from the property. The nearest airport is Penang International Airport, 12km.",
    // duration: "",
    hotel_class: 5,
    rating: 8.5,
    total_review: "46", 
    tags: ["penang"],
  },
  { 
    id: 46, 
    code: "HOTELS-MEL46-LSP",
    name: "Lexis Suites Penang",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FLexis-Suites-Penang%2CTeluk-Kumbar%2CMalaysia-c316769-h853092-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/a5/2f/17/expediav2-853092-c7334a-528193.jpg?width=968&height=607&crop=true",
    price: 576,
    currency: "MYR",
    description: "Nestled on the beach, this Bayan Lepas hotel is within 6 mi (10 km) of Snake Temple, Penang International Sports Arena and RECSAM and Institute Pendidikan Guru. University of Science-Malaysia (Universiti Sains Malaysia) and Queensbay Mall are also within 9 miles (15 km).",
    // duration: "",
    hotel_class: 5,
    rating: 8.3,
    total_review: "2,881", 
    tags: ["penang"],
  },
  { 
    id: 47, 
    code: "HOTELS-MEL47-PHP",
    name: "The Prestige Hotel Penang",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FThe-Prestige-Hotel-Penang%2CGeorge-Town%2CMalaysia-c4178-h5271314-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/1d/cf/52/leonardo-2102947-04_lobby_O-258582.jpg?width=968&height=607&crop=true",
    price: 628,
    currency: "MYR",
    description: "Located in Downtown George Town, this luxury hotel is within a 10-minute walk of Pinang Peranakan Mansion and Penang City Hall. KOMTAR and Penang Times Square are also within 2 miles (3 km).",
    // duration: "",
    hotel_class: 5,
    rating: 8.8,
    total_review: "2,098", 
    tags: ["penang"],
  },
  { 
    id: 48, 
    code: "HOTELS-MEL48-ASP",
    name: "Amari Spice Penang",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FAmari-Spice-Penang%2CBayan-Lepas%2CMalaysia-c324992-h8801607-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/87/b5/6b/expediav2-8801607-dc3586-829845.jpg?width=968&height=607&crop=true",
    price: 392,
    currency: "MYR",
    description: "Amari SPICE Penang offers an infinity pool as well as a pool-side bar. It also provides free private parking on site and Universiti Sains Malaysia and Jerejak are a brief car trip away. Guests can enjoy a range of massage treatments and beauty therapy at the on-site spa and wellness centre, Breeze Spa. Complimentary wireless internet is available for those wanting to stay online while travelling. The hotel also has its very own gym, Swimming pool. Each room is equipped with a coffee maker, slippers and a mini bar. All are air conditioned and feature a flat-screen TV, a seating area and a laptop safe. Amari SPICE Penang houses Amaya Food Gallery, which serves breakfast, lunch and dinner and presents guests with all they need for an enjoyable night within the hotel. Packed lunches are available on request for those with day trips planned. Within a 20-minute drive of the Penang Bridge and Penang International Airport, Amari SPICE Penang provides an airport shuttle service for its guests. It is also a short drive from George Town and Gelugor.",
    // duration: "",
    hotel_class: 5,
    rating: 8.8,
    total_review: "1,494", 
    tags: ["penang"],
  },
  { 
    id: 49, 
    code: "HOTELS-MEL49-SLR",
    name: "Shangri-La Rasa Sayang, Penang",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FShangri-La-Rasa-Sayang%2CPenang%2CGeorge-Town%2CMalaysia-c4178-h32620-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/0c/92/99/revato-9933-12547113-299662.jpg?width=968&height=607&crop=true",
    price: 825,
    currency: "MYR",
    description: "Nestled on the beach, this George Town resort is within 2 mi (3 km) of Ferringgi Beach and Tropical Spice Garden. ESCAPE Adventureplay and Entopia by Penang Butterfly Farm are also within 6 mi (10 km).",
    // duration: "",
    hotel_class: 5,
    rating: 8.6,
    total_review: "2,629", 
    tags: ["penang"],
  },
  { 
    id: 50, 
    code: "HOTELS-MEL50-HTB",
    name: "Hompton By The Beach Penang",
    link: "https://kayak.com.ar/in?a=kan_262812_573418&lc=es&url=%2Fhotels-dateless%2FHompton-By-The-Beach-Penang%2CTanjung-Bungah%2CMalaysia-c302939-h4895887-details%2F1rooms%2F2adults", 
    image: "https://www.kayak.com.my/rimg/himg/66/02/fd/expediav2-4895887-299244034-667741.jpg?width=968&height=607&crop=true",
    price: 334,
    currency: "MYR",
    description: "Located in Tanjung Bungah, this hotel is 0.1 mi (0.1 km) from Penang Avatar Secret Garden and 2.8 mi (4.5 km) from Wat Chaiya Mangkalaram. Camera Museum and Fort Cornwallis are also within 6 mi (10 km).",
    // duration: "",
    hotel_class: 5,
    rating: 8.5,
    total_review: "4,707", 
    tags: ["penang"],
  },
];