export const featuredData = [
  {
    id:"25",
    title: "1-Day Kuala Lumpur...",
    description: "Embark on a 1 day tour to the bustling city of Kuala Lumpur...",
    destinatio: 'Kuala Lumpur',
    author: "Aliahchase",
    image: "https://media.tacdn.com/media/attractions-splice-spp-674x446/0a/31/85/81.jpg",
    alt: "kltour",
    theme: 1,
    message: 'Kuala Lumpur',
    days: '5',
    tags: ["Fruit Valley", "Rainforest", "+1"],
    saves: 293,
    url: ""
  },
  {
    id: "26",
    title: "1-Day Adventure in...",
    description: "Start your 1 day Malaysian adventure with a thrilling... ",
    destinatio: 'Gopeng',
    author: "Aliahchase",
    image: "https://media.tacdn.com/media/attractions-splice-spp-674x446/11/cb/45/d0.jpg",
    alt: "cameron",
    theme: 1,
    message: 'Cameron Highland',
    days: '3',
    tags: ["Rivers", "Water Park", "Forest Park"],
    saves: 311,
    url: ""
  },
  {
    id: "27",
    title: "1-Day Exploration of...",
    description: "Indulge in a 1-day memorable journey through...",
    destinatio: 'Kuala Lumpur',
    author: "Aliahchase",
    image: "https://media.tacdn.com/media/attractions-splice-spp-674x446/07/70/cf/24.jpg",
    alt: "batucaves",
    theme: 1,
    message: 'Batu Caves',
    days: '1',
    tags: ["Theme Park", "Nature Park", "+1"],
    saves: 123,
    url: ""
  },
  {
    id: "28",
    title: "1-Day Cultural and...",
    description: "Embark on a 1-day journey to explore the fascinating...",
    destinatio: 'Kuala Lumpur',
    author: "Aliahchase",
    image: "https://media.tacdn.com/media/attractions-splice-spp-674x446/0b/df/b9/01.jpg",
    alt: "kuala selangor",
    theme: 1,
    message: 'Kuala Selangor',
    days: '1',
    tags: ["Galleries", "Memorial", "Palace"],
    saves: 222,
    url: ""
  },
  {
    id: "29",
    title: "1-Day Charimatic...",
    description: "Embark on a 1-day journey exploring the historic, culinary...",
    destinatio: 'Kuala Lumpur',
    author: "Aliahchase",
    image: "https://media.tacdn.com/media/attractions-splice-spp-674x446/10/5e/3c/31.jpg",
    alt: "kuala selangor",
    theme: 1,
    message: 'Kuala Selangor',
    days: '1',
    tags: ["Food Outlet", "Shopping", "+3"],
    saves: 222,
    url: ""
  },
  {
    id: "30",
    title: "1-Day Essential Kuala...",
    description: "Explore the vibrant heart of Malaysia with this 1-day tour of Kuala...",
    destinatio: 'Kuala Lumpur',
    author: "Aliahchase",
    image: "https://media.tacdn.com/media/attractions-splice-spp-674x446/0b/2c/f7/e9.jpg",
    alt: "kltour",
    theme: 1,
    message: 'Kuala Lumpur',
    days: '5',
    tags: ["Central Marks", "+3"],
    saves: 293,
    url: ""
  },
  {
    id: "31",
    title: "1-Day Kuala Lumpur...",
    description: "Dip into vibrant rhythm of Kuala Lumpur in this engaging 1-day tour... ",
    destinatio: 'Kuala Lumpur',
    author: "Aliahchase",
    image: "https://media.tacdn.com/media/attractions-splice-spp-674x446/06/71/3d/e0.jpg",
    alt: "cameron",
    theme: 1,
    message: 'Cameron Highland',
    days: '3',
    tags: ["Diving Beach", "Zoo", "Aquaria", "+1"],
    saves: 311,
    url: ""
  },
  {
    id: "32",
    title: "1-Day Kuala Lumpur...",
    description: "Uncover the stunning array of nature and wildlife Kuala Lumpur...",
    destinatio: 'Kuala Lumpur',
    author: "Aliahchase",
    image: "https://media.tacdn.com/media/attractions-splice-spp-674x446/0b/39/c1/e7.jpg",
    alt: "kuala selangor",
    theme: 1,
    message: 'Kuala Selangor',
    days: '1',
    tags: ["Rainforest", "Island", "+2"],
    saves: 222,
    url: ""
  },
  {
    id: "33",
    title: "1-Day Adventure and...",
    description: "This 1-day tour offers a comprehensive exploration...",
    destinatio: 'Kuala Lumpur',
    author: "Aliahchase",
    image: "https://media.tacdn.com/media/attractions-splice-spp-674x446/09/19/8e/c1.jpg",
    alt: "kuala selangor",
    theme: 1,
    message: 'Kuala Selangor',
    days: '1',
    tags: ["Hills", "Recreational Forest", "+2"],
    saves: 222,
    url: ""
  },
  {
    id: "34",
    title: "1-Day Exquisite Discovery...",
    description: "This exhalirating 1-day tour planned meticulously will take...",
    destinatio: 'Kuala Lumpur',
    author: "Aliahchase",
    image: "https://media.tacdn.com/media/attractions-splice-spp-674x446/0b/e6/5f/d5.jpg",
    alt: "kuala selangor",
    theme: 1,
    message: 'Kuala Selangor',
    days: '1',
    tags: ["Water Park", "Wetland Park", "+3"],
    saves: 222,
    url: " "
  },
];